name: Trigger E2E tests

permissions:
  contents: read
  actions: write
  pull-requests: write

on:
  issue_comment:
    types: [created]
  push:
    branches:
      - enes/e2e-run-command-test

jobs:
    pr_comment:
      runs-on: ubicloud
      steps:
        - name: Trigger E2E tests
          uses: actions/github-script@v7
          with:
            script: |
              const contributors = await github.rest.repos.listContributors({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              const contributorsLogins = contributors.data.map(c => c.id);
              console.log(contributorsLogins);

              process.exit(1);


              // Add a reaction to confirm that it's checking
              github.rest.reactions.createForIssueComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: context.payload.comment.id,
                content: 'rocket'
              })

              // Create a workflow dispatch event
              const testCases = context.payload.comment.body.split(' ')[1]
              const inputs = testCases ? { test_cases: testCases } : {}
              github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: 'e2e.yml',
                ref: context.ref,
                inputs: inputs
              });
